[package]
name = "rollout"
version = "0.0.2"
authors = ["Max Jacobson <max@hardscrabble.net>"]
readme = "README.md"
description = "A feature flipper library"
license = "MIT"

[dependencies]
redis = "0.8"
